preload=/home/cmdr/.wallpaper/2CB.png
preload=/home/cmdr/.wallpaper/SYSTEMA.png
preload=/home/cmdr/.wallpaper/colorshift_vert.png
#preload=/home/cmdr/.wallpaper/colorshift.png
#wallpaper=DP-1,/home/cmdr/.wallpaper/SYSTEMA.png
#wallpaper=eDP-1,/home/cmdr/.wallpaper/2CB.png
#wallpaper=HDMI-A-1,/home/cmdr/.wallpaper/colorshift.png

wallpaper {
    monitor = DP-2
    path = ~/.wallpaper/SYSTEMA.png
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    path = ~/.wallpaper/2CB.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/.wallpaper/colorshift_vert.png
    fit_mode = cover
}