console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  yellowMain = '#f1e713'
  yellowDarker = '#d8d62b'
  yellowLight = '#beca5e'
  yellowGray = '#a1bc79'
  BlueGray = '#71a797'
  blueBright = '#1f839b'
  blueDark = '#103c55'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'path'
    style = 'diamon'
    powerline_symbol = '\ue0c7'
    foreground = 'p:yellowMain'
    background = '#61AFEF'

    [blocks.segments.properties]
      style = full